### ISSUE TITLE
막노트

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#15]
떠오른 아이디어. 그냥 잡 생각. 앞으로의 계획.
뭐든 상관없으니, 일단 여기에 적고 보자. 쓸데없는 아이디어라도 일단 기록을 해놓아야 서로 공유를 할 수 있다.

**Comment by eubinecto** [comment]
영어 -> 우리말 속담
우리말 ->  영어 속담

이렇게 cross-lingual reverse-dictionary를 만드는 것도 좋지 않을까?

**Comment by eubinecto** [comment]
우리말 속담을 여러 주제로 분류할 수도 있다.
e.g. [가난과 관련된 속담](https://blog.daum.net/ikhyuk/7352917)
- 가난과 거지는 사촌간이다
- 가난도 비단가난
- 가난도 스승이다
등등..

이런 분류체계를 찾거나, 우리가 직접 만들 수 있다면, feature engineering에 활용할 수도 있을 것. 예를 들면 그렇게 속담을 분류하는 classification loss를 최종 loss에 추가하는 식.

**Comment by eubinecto** [comment]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/56193069/124601642-0b90b300-dea3-11eb-8ec5-d2a630ef85fe.png">

transfer learning의 장점을 보여주는 단적인 예시

**Comment by eubinecto** [comment]
님의 제안:
클래스가 많을 때, 성능향상을 꾀할 수 있는 방법론이 있다.
@teang1995 님, 여기에다가 관련 논문 추가해주세요!

**Comment by teang1995** [comment]
> 님의 제안:
> 클래스가 많을 때, 성능향상을 꾀할 수 있는 방법론이 있다.
> @teang1995 님, 여기에다가 관련 논문 추가해주세요!

https://pageperso.lis-lab.fr/thierry.artieres/wp-content/uploads/2018/09/BigDataWshp_v2.pdf
우선 괜찮은 피피티를  찾아 공유합니다!

**Comment by eubinecto** [comment]
매주 일요일,  새로운 모델 & 데이터 버전 (e.g. `version_0`, `version_1`)을 릴리즈 하는 것을 목표로 하면 좋을 것 같다.
각 버전은 이전 버전의 incremental update.

**Comment by eubinecto** [comment]
> 영어 -> 우리말 속담
> 우리말 -> 영어 속담
> 
> 이렇게 cross-lingual reverse-dictionary를 만드는 것도 좋지 않을까? 사실 논문을 쓴다고 한다면, 영어 -> 영어 속담이 더 유리한 주제일 수도 있다.
> 
> 하지만 english proverbs의 문제:
> <img alt="image" width="421" src="https://user-images.githubusercontent.com/56193069/124587706-e6944400-de92-11eb-90ca-3667a8e70c66.png">
> 우리말 속담 처럼 구분자가 확실하지는 않음. 또 variation이 별로 없는 우리말 속담과는 달리, 영어 속담은 variation이 자주 일어남 (e.g. jack of a ll trades, but master of most).
> 
> 일단, mono-lingual 모델 개발에 집중을 하고 완성도 높은 mono-lingual model을 만들면, cross-lingual로 전환하는 것은 그리 어려운 일이 아닐 것.

cross-lingual에 대해 생각하기 전에, 일단 mono-lingual에 집중을 하자.

영어를 다루지 못하는 것이 아쉽다면, eng-to-eng wisdomify를 구현하는 것은 쉽사리 할 수 있을 것이다. 물론 앞서 언급했던 "분명하지 않은 구분자" 문제를 해결하긴 해야겠지만은.

그 문제는 차치하고, 어찌되었든 옥스포드에서 편찬한 dictionary of  english proverbs가 있다:
- https://www.oxfordreference.com/view/10.1093/acref/9780199539536.001.0001/acref-9780199539536

example entry:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/56193069/124690761-9dd19f00-df15-11eb-935f-2e721f633608.png">

**Comment by teang1995** [comment]
> 클래스가 많을 때, 성능향상을 꾀할 수 있는 방법론이 있다.
> @teang1995 님, 여기에다가 관련 논문 추가해주세요!

large number of classes classification 에 대해 찾아보니 "superclass"를 지정하는 방식을 많이 사용한다고 한다.
[CIFAR100](https://www.cs.toronto.edu/~kriz/cifar.html)
[Hierarchical Auxiliary Learning](https://arxiv.org/pdf/1906.00852.pdf) (한국 분들이 쓴 논문!)
등등..

이에 착안하여 사전 학습된 BERT 를 이용해 피쳐를 뽑은 뒤, [unknown number of centroid clustering](https://stats.stackexchange.com/questions/14955/any-suggestion-for-clustering-method-for-unknown-number-of-clusters-and-non-eucl)을 해주면  superclass 처럼 사용할 수 있지 않을까 생각했다.

물론 가장 좋은 방법은 검증된 방법으로, 혹은 한국어 및 한국어 속담에 통달하신 분이 분류해놓은 방법을 따라가는 것인데, 
[세계 속담 대사전 : 주제별 비교 분류](https://www.nl.go.kr/NL/contents/search.do?srchTarget=total&pageNum=1&pageSize=10&kwd=%EC%84%B8%EA%B3%84%EC%86%8D%EB%8B%B4%EB%8C%80%EC%82%AC%EC%A0%84#viewKey=412892&viewType=AH1&category=%EB%8F%84%EC%84%9C&pageIdx=1) 라는 자료가 국립중앙도서관에 있는 것을 확인하였다!

논의해보아야 알겠지만, 필요하다면 요청해볼 생각.

**Comment by ArtemisDicoTiar** [comment]
>>
> 물론 가장 좋은 방법은 검증된 방법으로, 혹은 한국어 및 한국어 속담에 통달하신 분이 분류해놓은 방법을 따라가는 것인데,
> [세계 속담 대사전 : 주제별 비교 분류](https://www.nl.go.kr/NL/contents/search.do?srchTarget=total&pageNum=1&pageSize=10&kwd=%EC%84%B8%EA%B3%84%EC%86%8D%EB%8B%B4%EB%8C%80%EC%82%AC%EC%A0%84#viewKey=412892&viewType=AH1&category=%EB%8F%84%EC%84%9C&pageIdx=1) 라는 자료가 국립중앙도서관에 있는 것을 확인하였다!
> 
> 논의해보아야 알겠지만, 필요하다면 요청해볼 생각.

오오 좋은 자료 감사합니다 :) 안그래도 한글 속담 주제별 분류로 자료 찾기 힘들어서 국립국어원에 관련 자료 있나 문의하려고 했었는데 해당 서적으로 데이터를 구축할 수 있으면 베스트겠어요! XD

**Comment by eubinecto** [comment]
굳이 data를 이렇게 나누어야하나?:
```python3

    # --- the type of wisdomifier --- #
    if data == "wisdom2def":
        wisdom2sent = load_wisdom2def()
        model_name = "wisdomify_def_{epoch:02d}_{train_loss:.2f}"
    elif data == "wisdom2eg":
        wisdom2sent = load_wisdom2eg()
        model_name = "wisdomify_eg_{epoch:02d}_{train_loss:.2f}"
    else:
        raise NotImplementedError("Invalid data provided")

```
정의를 학습한 모델 따로, 용례를 학습한 모델도 따로 maintain을 해야하나? 일단은 그렇게 짜놓기는 했는데..음...
둘을 합치는게 나을까? 상관없을까? 이거 고민이네.

**Comment by eubinecto** [comment]
## refactoring

나중 일이겠지만,  `vocab`자체를 모델안에 집어넣는 편이 나을 것.
그럼 굳이..  `vocab2subwords`를 인자로 받을 일이 없다.

**Comment by teang1995** [comment]
> > 클래스가 많을 때, 성능향상을 꾀할 수 있는 방법론이 있다.
> > @teang1995 님, 여기에다가 관련 논문 추가해주세요!
> 
> large number of classes classification 에 대해 찾아보니 "superclass"를 지정하는 방식을 많이 사용한다고 한다.
> [CIFAR100](https://www.cs.toronto.edu/~kriz/cifar.html)
> [Hierarchical Auxiliary Learning](https://arxiv.org/pdf/1906.00852.pdf) (한국 분들이 쓴 논문!)
> 등등..
> 
> 이에 착안하여 사전 학습된 BERT 를 이용해 피쳐를 뽑은 뒤, [unknown number of centroid clustering](https://stats.stackexchange.com/questions/14955/any-suggestion-for-clustering-method-for-unknown-number-of-clusters-and-non-eucl)을 해주면 superclass 처럼 사용할 수 있지 않을까 생각했다.
> 
> 물론 가장 좋은 방법은 검증된 방법으로, 혹은 한국어 및 한국어 속담에 통달하신 분이 분류해놓은 방법을 따라가는 것인데,
> [세계 속담 대사전 : 주제별 비교 분류](https://www.nl.go.kr/NL/contents/search.do?srchTarget=total&pageNum=1&pageSize=10&kwd=%EC%84%B8%EA%B3%84%EC%86%8D%EB%8B%B4%EB%8C%80%EC%82%AC%EC%A0%84#viewKey=412892&viewType=AH1&category=%EB%8F%84%EC%84%9C&pageIdx=1) 라는 자료가 국립중앙도서관에 있는 것을 확인하였다!
> 
> 논의해보아야 알겠지만, 필요하다면 요청해볼 생각.

![image](https://user-images.githubusercontent.com/23451721/124878005-9938e380-e006-11eb-8acb-221a3b095043.png)
자세히 보질 않아 목차까지 보지 못 했는데, 위와 같이 사실상 주제에 관한 분류가 끝마쳐져 있어 텍스트로 옮길 수만 있다면 빠른 속도로 분류가 가능할 것으로 보인다.
제발 텍스트를 구할 수 있었으면 좋겠다.

**Comment by eubinecto** [comment]
모델 & 데이터를 같이 묶어서 verson control을 할수 있는 방법이 있다(?!).
구글 클라우드와 연동이 되는듯. 이걸 활용을 해서.. 버전 컨트롤을 해보자.

**Comment by eubinecto** [comment]
바로바로 커뮤니케이션을 하기위해선  깃헙 대댓으로는 좀 그럼.
나중에 다같이 소통할 수 있는 슬랙 채널을 하나파자.

**Comment by teang1995** [comment]
> > > 클래스가 많을 때, 성능향상을 꾀할 수 있는 방법론이 있다.
> > > @teang1995 님, 여기에다가 관련 논문 추가해주세요!
> > 
> > 
> > large number of classes classification 에 대해 찾아보니 "superclass"를 지정하는 방식을 많이 사용한다고 한다.
> > [CIFAR100](https://www.cs.toronto.edu/~kriz/cifar.html)
> > [Hierarchical Auxiliary Learning](https://arxiv.org/pdf/1906.00852.pdf) (한국 분들이 쓴 논문!)
> > 등등..
> > 이에 착안하여 사전 학습된 BERT 를 이용해 피쳐를 뽑은 뒤, [unknown number of centroid clustering](https://stats.stackexchange.com/questions/14955/any-suggestion-for-clustering-method-for-unknown-number-of-clusters-and-non-eucl)을 해주면 superclass 처럼 사용할 수 있지 않을까 생각했다.
> > 물론 가장 좋은 방법은 검증된 방법으로, 혹은 한국어 및 한국어 속담에 통달하신 분이 분류해놓은 방법을 따라가는 것인데,
> > [세계 속담 대사전 : 주제별 비교 분류](https://www.nl.go.kr/NL/contents/search.do?srchTarget=total&pageNum=1&pageSize=10&kwd=%EC%84%B8%EA%B3%84%EC%86%8D%EB%8B%B4%EB%8C%80%EC%82%AC%EC%A0%84#viewKey=412892&viewType=AH1&category=%EB%8F%84%EC%84%9C&pageIdx=1) 라는 자료가 국립중앙도서관에 있는 것을 확인하였다!
> > 논의해보아야 알겠지만, 필요하다면 요청해볼 생각.
> 
> ![image](https://user-images.githubusercontent.com/23451721/124878005-9938e380-e006-11eb-8acb-221a3b095043.png)
> 자세히 보질 않아 목차까지 보지 못 했는데, 위와 같이 사실상 주제에 관한 분류가 끝마쳐져 있어 텍스트로 옮길 수만 있다면 빠른 속도로 분류가 가능할 것으로 보인다.
> 제발 텍스트를 구할 수 있었으면 좋겠다.

문득 든 생각인데 수집할 속담 약 8000개가 과연 저 분류에서 균일한 비율로 뽑힐까? 하는 고민이 스침.
superclass의 class간 imbalance가 문제가 될지에 대해 찾아보아야 함.

**Comment by eubinecto** [comment]
막노트는 슬랙에서 이어서... !
