### ISSUE TITLE
version 0 deploy

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/wisdomify#25]

**Comment by ArtemisDicoTiar** [comment]
> > > 아, 그러면 모델을 로드해놓고 계속 유지하는 방법만 찾으면, inference는 빠르게 할 수 있을 듯!
> > 
> > 
> > 예스예스 아마 alpha service정도 deploy하는 단계가 되면 도커내에 데몬처럼 띄워놓고 request가 오면 처리하는 식으로 될듯.
> > https://github.com/hanxiao/bert-as-service 이 리포에서 속도가 빠른이유도 모델을 로드 미리 데몬형태로 해놓고 각 데몬이 infer처리만 해서 그런듯.
> > (모델 로드까지 한 데몬을 병렬워커(n개, 리드미 예제에서는 6~8개)를 띄운후에 클라이언트에서 요청이오면 각 요청별로 워커가 담당해서 처리)
> > 저 리포 한번 뒤적거리면서 사용해보고 괜찮으면 디플로이 단계에서 사용하면 될거 같음! :)
> 
> ainize 플랫폼에 bert-as-a-service를 활용해서 version_0를 deploy하는 것이 가능할까?

**Comment by ArtemisDicoTiar** [comment]
어쨋든 실행은 main에서 할거라 main에 deploy.py파일 생성!

**Comment by ArtemisDicoTiar** [comment]
그냥 플라스크나 장고로 디플로이 할까...
텐서플로우 버전을 꽤 낮게 내려야할것 같은데 파이썬 버전이 3.8이라 텐서플로우 2.5버전이하로 내릴수가 없다 ㅠ

**Comment by ArtemisDicoTiar** [comment]
그냥 플라스크 써야겠다 
토치서브 사용하려면 핸들러를 작성해줘야하는 데 거의 플라스크 작성하는 정도로 적어야하고 모델도 .MAR포맷으로 변환해줘야한다. ㅠㅠ

**Comment by eubinecto** [comment]
streamlit으로 해보는건??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArtemisDicoTiar** [comment]
streamlit을 이용하려 했으나 얘로 실행하기 위한 설정 오버헤드가 커보임.
플라스크 단일 파일로 version_0 구현 완료.


![Screenshot 2021-07-20 at 17 41 46](https://user-images.githubusercontent.com/47541511/126362864-5f52fd1a-07d3-4acf-ab94-14da2495e2bb.png)


### Ainize 배포 준비 
- [ ] 도커파일 작성

**Comment by ArtemisDicoTiar** [comment]
* wget 이 제대로 작동하지 않음. curl로 변경
* dropbox DL 링크 사용시에는 반드시 dl=1 쿼리 파라미터를 넣어야한다.

**Comment by ArtemisDicoTiar** [comment]
* health check용 엔드포인트가 있어야하나보다 다들 가지고 있네..
~~~python

@app.route('/healthz', methods=['GET'])
def checkHealth():
    return "Alive", 200
~~~

**Comment by ArtemisDicoTiar** [comment]
app.run(..., debug=False, ...)

**Comment by ArtemisDicoTiar** [comment]
휴... 디플로이 성공.
https://issue-25-wisdomify-eubinecto.endpoint.ainize.ai/search?desc=%ED%8E%A9%EC%8B%9C%EB%A7%90%EA%B3%A0+%EC%BD%94%EC%B9%B4%EC%BD%9C%EB%9D%BC%EB%82%98+%EB%A7%88%EC%8B%9C%EC%9E%90+%EC%A0%9C%EB%B0%9C
