### ISSUE TITLE
Versioning Rule 정하기

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/wisdomify#30]
## Why?
- 참고: [ Semantic Versioning 소개](https://spoqa.github.io/2012/12/18/semantic-versioning.html)

버전네이밍에 보편적인 규칙이 없으면, 버전에 따른 의미해석이 제각기 달라 어려워진다. 혼자서 개발한다면 문제 없겠지만,
여럿이서 협력을 하는 프로젝트에서는 누군가 "이번 릴리즈는 1.2.3 -> 1.3.3 입니다" 라고 했을 때, 두번째 숫자가 하나올라가는 것의 의미를 모두가 알고 있지 않다면 생산성이 떨어질 것.

## What?
https://github.com/eubinecto/wisdomify/issues/30#issuecomment-888552287 종윤님께서 코멘트하신 것처럼, 각 버전이 의미하는바를 확실하게 정하고, @teang1995 @eubinecto @ArtemisDicoTiar  모두가 숙지해두도록하자.

**Comment by ArtemisDicoTiar** [comment]
X.Y.Z
Z++ → 패치버전 (하위 호환 하지만 버그 수정이 있을때.)
Y++ → 새로운 기능 추가 but 기존의 버전이 하위호환할 때 (기능이 deprecated 될때도)
X++ → 하위호환 되지 않는 기능, 변화가 추가될 때.

**Comment by eubinecto** [comment]
참고자료를 확인해보니 -  노드, PHP, Python, Ruby 모두 semantic versioning rule을 따르고 있다고 함.

위 참고자료의 맺는 말에 공감이 간다.
>  비록 작은 통일일지는 모르나, 버전 명을 작성하는 훌륭한 기준이 있다는 것은 장기적으로 개발 생태계를 더욱 빠르고 긴밀하게 협력하도록 도와줄 것이라 생각됩니다. 의미적 해석이 가능한 코드는 **의존성 문제를 더 똑똑한 수준으로 자동화할 수 있기 때문이죠.** 버전 명을 지으실 때 좋은 안내서가 되었으면 좋겠습니다.

현재는 별 고민을 안하고 있긴 하지만, 의존성에 대한 고민을 할날이 혹시 올지도 모르니. 이 규칙을 따르는 것에 찬성!
@ArtemisDicoTiar 덕분에 새로운 것을 배웠다!

**Comment by eubinecto** [comment]
@teang1995 용택님 확인해주세요! ㅎㅎ

**Comment by teang1995** [comment]
확인했습니다!

**Comment by eubinecto** [comment]
모두 숙지했으니 클로징하겠음!
