### ISSUE TITLE
[Error] requirements 설치 시 에러 발생

### ISSUE THREAD

**Issue by teang1995** [eubinecto/wisdomify#36]
## 환경
apple mac book air m1
![스크린샷 2021-08-05 오후 9 24 24](https://user-images.githubusercontent.com/23451721/128349423-bc4dd00e-ecb1-4347-a550-715e2cdc39f9.png)

## 증상
pip install requirements 시 아래 사진과 같은 오류가 발생하며 grpcio가 설치되지 않음.
![스크린샷 2021-08-05 오후 9 26 37](https://user-images.githubusercontent.com/23451721/128349693-b62f4acd-7baa-4222-bb85-22b9197f1aeb.png)

**Comment by ArtemisDicoTiar** [comment]
잠시만요 저거 아마 제가 디플로이하다 생긴 그걸 거 같은데 requirements 수정해둘게요!

**Comment by teang1995** [comment]
> 잠시만요 저거 아마 제가 디플로이하다 생긴 그걸 거 같은데 requirements 수정해둘게요!

넵 알겠습니다 잠시 기다리겠습니다 ㅎㅎ

**Comment by ArtemisDicoTiar** [comment]
> > 잠시만요 저거 아마 제가 디플로이하다 생긴 그걸 거 같은데 requirements 수정해둘게요!
> 
> 넵 알겠습니다 잠시 기다리겠습니다 ㅎㅎ

헛 ㅋㅋㅋ 방금 확인해봤는데 제가 설치해서 추가한게 아니네요 문제 해결을 해봐야할거 같아요

그 @teang1995 용택님 혹시 맥에 xcode나 gcc 설치 되어 있나요?

**Comment by teang1995** [comment]
> > > 잠시만요 저거 아마 제가 디플로이하다 생긴 그걸 거 같은데 requirements 수정해둘게요!
> > 
> > 
> > 넵 알겠습니다 잠시 기다리겠습니다 ㅎㅎ
> 
> 헛 ㅋㅋㅋ 방금 확인해봤는데 제가 설치해서 추가한게 아니네요 문제 해결을 해봐야할거 같아요
> 
> 그 @teang1995 용택님 혹시 맥에 xcode나 gcc 설치 되어 있나요?

![스크린샷 2021-08-05 오후 9 32 43](https://user-images.githubusercontent.com/23451721/128350543-f8bfdf89-cd5c-470b-b8c6-2f7b5ff01dc8.png)
넵 gcc는 설치되어있습니다! xcode도 설치되어있네요

**Comment by teang1995** [comment]
> > > 잠시만요 저거 아마 제가 디플로이하다 생긴 그걸 거 같은데 requirements 수정해둘게요!
> > 
> > 
> > 넵 알겠습니다 잠시 기다리겠습니다 ㅎㅎ
> 
> 헛 ㅋㅋㅋ 방금 확인해봤는데 제가 설치해서 추가한게 아니네요 문제 해결을 해봐야할거 같아요
> 
> 그 @teang1995 용택님 혹시 맥에 xcode나 gcc 설치 되어 있나요?
> 
> 지금 찾아보니 M1 맥에서 이슈가 있는 거 같네요 ㅠㅠ
> ([grpc/grpc#24677 (comment)](https://github.com/grpc/grpc/issues/24677#issuecomment-875073847))

첨부해주신 이슈 보고 해결해보겠습니다 ㅎㅎ 유빈님은 이 문제가 있었을지 궁금하네요.. 해결하면 결과 공유하겠습니다-!

**Comment by teang1995** [comment]
`GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 pip install -r requirements.txt
`
와 같이 requirements 를 설치해주니 잘 실행됩니다 ㅎㅎ 종윤님 도움 감사드려요!
언급해주신 이슈와 https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop 
를 함께 참고하여 해결하였습니다

**Comment by ArtemisDicoTiar** [comment]
러스트도 설치해야한다 ㅋㅋㅋ

**Comment by eubinecto** [comment]
다음의 코멘트에서 발견함:
https://github.com/huggingface/transformers/issues/2831#issuecomment-600141935

**Comment by eubinecto** [comment]
터미널을 리스타트 해야할수도? https://github.com/huggingface/transformers/issues/2831#issuecomment-600141935

**Comment by ArtemisDicoTiar** [comment]
~~~
CFLAGS="-I /opt/homebrew/opt/openssl/include" LDFLAGS="-L /opt/homebrew/opt/openssl/lib" GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 pip install -r requirements.txt
~~~

**Comment by eubinecto** [comment]
정리하자면.

1. brew install gcc
2. install rust
3. https://github.com/eubinecto/wisdomify/issues/36#issuecomment-894197365

하니까 되더라!
