### ISSUE TITLE
storyteller에서 데이터 가져오는 로직 만들기

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/wisdomify#37]
## Why?
storyteller에서 데이터 수집하고 저장하는 위치를 .tsv(.csv)에서 개인 MariaDB로 변경했다.
이 변경 사항으로 인해 앞으로 데이터를 DB에서 원하는 포맷으로 뽑고 피쳐 엔지니어링을 할 수 있게 하는 로직이 필요하다.

## What?
data_downloader와 raw_data_pre_processor를 작성해야한다.

**Comment by eubinecto** [comment]
참고) 수집할 때는 버전신경 X

**Comment by ArtemisDicoTiar** [comment]
데이터 로드하는 작업 허깅페이스 통해서 하도록 수정할 예정.
여기서 스토리텔러로 직접 로드할 필요없음.

1. 스토리 텔러에서 허깅페이스로 업로드하는 코드
2. 스토리 텔러에서 피쳐 엔지니어링 하는 코드 
3. 피쳐 엔지니어링해서 버저닝되는 파일들 허깅 페이스로 업로드

이렇게 해서 데이터 관련한 작업은 스토리텔러로 이전.

**Comment by ArtemisDicoTiar** [comment]
해당 이슈 클로징.
