### ISSUE TITLE
버전 통합하기 &  Resolving Conflict

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#38]
## Why?
첫쨰로, 데이터가 버전별로 관리되고 있지 않음. (wisdom2def.tsv, wisdom2eg.tsv. 버전 없음). 이는 향후 새로운 버전의 데이터가 추가되었을 때 문제가 될 수 있음.

---
https://github.com/eubinecto/wisdomify/blob/3f19e501172e71d35c5892fb6be925f0dea9b5c4/wisdomify/loaders.py#L7-L19
또한, `loaders.py`에서, 데이터를 버전에 맞게 불러올 수도 없다. 로더는 `ver`을 파라미터로 받지 않음.

---
https://github.com/eubinecto/wisdomify/blob/3f19e501172e71d35c5892fb6be925f0dea9b5c4/wisdomify/main/train.py#L40-L43
데이터와는 별개로, 모델 바이너리 파일 이름에 버전이 명시 X. 물론 모델 패키지로 버전을 관리하므로 큰 문제는 없지만.. 그래도 모델명에 버전 이름을 추가하면 좋을 것.

---
https://github.com/eubinecto/wisdomify/blob/3f19e501172e71d35c5892fb6be925f0dea9b5c4/conf.json#L6
`conf.json`에서도 사용한 데이터의 버전을 명시해야 할 것. 이걸 정확히 명시하면, 훈련할 때 가져온 데이터를 명시할 수 있음.

---
모델 버전과 데이터 버전이 따로간다? 그래야 하지 않을까?
모델 버전은... feature engineering만 해도 바뀔 수 있으므로. 데이터와 따로 관리하는 것이 좋을 것?

---
https://github.com/eubinecto/wisdomify/blob/7207446588e616d0ea0c838db86828fb56844357/wisdomify/main/infer.py#L29-L41
이렇게 여러줄에 걸쳐서 하나의 버전을 가져오는 것보단.. 

```python3
rd_ver_1 = RD.from_pretrained("version_1")
```
이렇게 하는게?

혹은 그냥 `Wisdomifier`클래스에 from_pretrained 정의하기.

## To-do's
- [x] 브랜치 생성 -> feature_38
- [x] loaders.py
- [x] #39
- [x] PR review: #32 
- [x] PR review: #33

**Comment by ArtemisDicoTiar** [comment]
## `loaders.py`
### 문제
`loaders.py`에 기존에는 `load_wisdom2def()` 와 `load_wisdom2eg()`가 함수로 구현되어 있었으며,
로드하고 싶은 파일을 paths.py에서 하드코딩된 채로 불러와졌기 때문에 버전 컨트롤이 되지 않았다.

### 해결
1. data 폴더에 wisdomdata라는 폴더 생성.
  1. 해당 폴더내에 version_{#버전 번호}라는 폴더 생성
  2. 버전별 폴더내에 'wisdom2def.tsv', 'wisdom2eg.tsv'로 데이터 입력.
2. `conf.json`에 데이터 버전을 모델 버전 내에 입력
3. `paths.py`에 데이터를 버전별로 로드하게끔 변수 생성
4.  `train.py`와 `eval.py`에 위에 작성한 버전에 맞게 데이터 보도록 수정.
