### ISSUE TITLE
eval 작동 안함

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/wisdomify#44]
## Why?
데이터 모듈 + 버전 컨트롤 넣은 뒤 eval이 작동안한다.

## What?
대충 찾아보니 모델에 test_step이란 걸 추가할 수 있는 거 같다

#### Form
~~~
batch:0 (0.0, 0.0, 1.0, 1.0, 1.0)
batch:1 (0.0, 0.0, 1.0, 1.0, 1.0)
### final ###
data: wisdom2def
median: 0.0
var: 0.0
top1: 1.0
top10: 1.0
top100: 1.0
~~~

**Comment by ArtemisDicoTiar** [comment]
## 데이터 셋...
잠깐만 이거 데이터로더를 트레이닝이랑 이벨이랑 따로 부르는데 이러면 테스트셋이 나머지랑 섞이지 않나?
랜덤 시드를 설정하면 괜찮아지려나?

**Comment by eubinecto** [comment]
> ## 데이터 셋...
> 잠깐만 이거 데이터로더를 트레이닝이랑 이벨이랑 따로 부르는데 이러면 테스트셋이 나머지랑 섞이지 않나?
> 랜덤 시드를 설정하면 괜찮아지려나?

랜덤 시드를 설정하기보단. 그냥... test, train을 미리 구축해놓는게 나을 것 같아.
예를 들면 이렇게:
```
wisdomdata
- version_1
  - wisdom2eg.tsv
  - wisdom2eg_train.tsv
  - wisdom2eg_val.tsv
  - wisdom2eg_test.tsv 
```

이런 파일들을, `widomify.main.split`에서 미리 생성을 해놓고. 이 파일들을 로드하면 "시드 설정 잘된건가..?" 걱정없이 테스트 돌릴 수 있을듯.

아울러 테스트 셋의 경우, 모든 모델 버전 별로 동일한 테스트 셋을 사용해야 비교에 용이하므로. `conf.json`에 현재 사용중인 
테스트 셋을 정의하면 좋을 것 같다:
```json
{
  # 예를 들면 이렇게?
  "test": "version_1/wisdom2eg_test.tsv + wisdom2def_test.tsv"
  " versions": {
  } 
}

```

**Comment by eubinecto** [comment]
> > ## 데이터 셋...
> > 잠깐만 이거 데이터로더를 트레이닝이랑 이벨이랑 따로 부르는데 이러면 테스트셋이 나머지랑 섞이지 않나?
> > 랜덤 시드를 설정하면 괜찮아지려나?
> 
> 랜덤 시드를 설정하기보단. 그냥... test, train을 미리 구축해놓는게 나을 것 같아.
> 예를 들면 이렇게:
> 
> ```
> stories
>   - version_1
>    - readme.md
>    - all
>      -  wisdom2eg.tsv
>      -  wisdom2def.tsv
>    - train
>      -  wisdom2eg_train.tsv
>      -  wisdom2def_train.tsv
>    - val
>      -  wisdom2eg_val.tsv
>      -  wisdom2def_val.tsv
>    - test
>      -  wisdom2eg_test.tsv
>      -  wisdom2def_test.tsv
> ```
> 
> 이런 파일들을, `widomify.main.split`에서 미리 생성(여기에서 random seed 사용)을 해놓고. 이 파일들을 로드하면 "시드 설정 잘된건가..?" 걱정없이 테스트 돌릴 수 있을듯.
> 
> 아울러 테스트 셋의 경우, 모든 모델 버전 별로 동일한 테스트 셋을 사용해야 비교에 용이하므로. `conf.json`에 현재 사용중인
> 테스트 셋을 정의하면 좋을 것 같다. 예를 들면 이렇게:
> 
> ```json
> {
>   "test": "stories/version_1/test",
>   " versions": {
>   } 
> }
> ```

허깅페이스 데이터 셋을 만드는 것이 나을듯 - https://wisdomify.slack.com/archives/C028DPZEN5P/p1628385373002700

**Comment by ArtemisDicoTiar** [comment]
~~~python
self.dataset_all.upsample(self.repeat)
        # 이 upsample은 전체 데이터 일때만 실행해야하는 것인가 아니면 나눠진 데이터에서 실행해도 상관없는 것인가?
        # min/max scaler같이 데이터의 값에 따라 달라지는 지 확인해야겠다.
        # 별 상관 없구나
~~~

**Comment by eubinecto** [comment]
밑에다가 load_dataset() 쓰는 방법 남겨주세요!

**Comment by ArtemisDicoTiar** [comment]
## How to use huggingface dataset

https://github.com/ArtemisDicoTiar/storyteller/issues/16
