### ISSUE TITLE
version_1 deploy on ainize

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/wisdomify#52]

**Comment by eubinecto** [comment]
@ArtemisDicoTiar  혹시 사이트에서 version_0, version_1을 선택할 수 있도록 할 수 있을까?

**Comment by ArtemisDicoTiar** [comment]
음... try해볼게

**Comment by eubinecto** [comment]
ㅋㅋㅋ 아니면 각 version 별로 다른 도메인을 만들어도 좋을 것 같아.

**Comment by ArtemisDicoTiar** [comment]
배포 완료
https://feature-52-wisdomify-eubinecto.endpoint.ainize.ai/
