### ISSUE TITLE
속담 Vocabulary 구축하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#7]
현재 사용하고 있는 vocabulary는 다음과 같은 10개의 속담이다:
https://github.com/eubinecto/wisdomify/blob/639cb221177d5ed05a2bd8a79ffa1378f71e68b9/wisdomify/vocab.py#L2-L13

물론 현용되는 우리말 속담은 이에 그치지 않는다. 적어도 1000개는 있을 것. 

이 10개 외에 어떤 우리말 속담을, 무엇을 기준으로 (e.g. timeliness) 찾을지에 대해 discuss 해보자.

-> 어떻게 중요한 속담으로 간추릴 수 있을까?

**Comment by eubinecto** [comment]
블로그 포스팅은 신뢰도가 떨어지기는 하지만, 일단 프로토타이핑에는 문제없이 사용할 수 있으므로, 우리말 속담 리스트를 정리한 블로그 포스트를 여기에 기록함:
  - [우리말 속담 1144가지](https://blog.daum.net/33063590/10603266)
  - [우리말 속담 100가지](https://blog.daum.net/kunghokungsea/1011)

찾다 보니 우리말 속담 사전 mobile app도 있다 - [우리말 속담 사전](https://play.google.com/store/apps/details?id=com.crystal.lab.koreanproverb&hl=ko&gl=US)
 
이 앱의 리뷰를 살짝 훑어봤는데:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/56193069/123579254-80fce380-d812-11eb-9da6-48dd329f1525.png">

보아하니 초/중학생들이 우리말 속담을 공부하기 위해서 종종 사용하는 것으로 보임. -> wisdomify도 이런 친구들에게 도움이 될 수 있지 않을까, 생각이 든다.

**Comment by ArtemisDicoTiar** [comment]
forward-dictionary 관련 repository: [ArtemisDicoTiar/wisdomTeller](https://github.com/ArtemisDicoTiar/wisdomTeller)

**Comment by eubinecto** [comment]
일단 https://github.com/eubinecto/wisdomify/issues/7#issuecomment-869618159 여기에서 속담 vocab 구축은 완료 했으므로,  closing the issue for now
